server:
  port: 8080

spring:
  application:
    name: customer

  profiles:
    active: dev

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true