spring:
  datasource:
    username: grobikon
    password: postgres
    url: jdbc:postgresql://localhost:5432/customer

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop