version: '3.1'

volumes:
  postgres:
  pgadmin:

networks:
  postgres:
    driver: bridge

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres-demo
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=grobikon
      - POSTGRES_DB=customer
      - PGDATA=/data/postgresql
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - postgres
  postgres-fraud:
    image: postgres
    restart: always
    container_name: postgres-fraud
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=grobikon
      - POSTGRES_DB=fraud
      - PGDATA=/data/postgresql
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - ${POSTGRES_PORT:-5433}:5432
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped