server:
  port: 8081

spring:
  application:
    name: fraud

  datasource:
    username: grobikon
    password: postgres
    url: jdbc:postgresql://localhost:5432/fraud

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true